### ISSUE TITLE
[Traefik Pilot] Traefik Plugin Analyzer has detected a problem.

### ISSUE THREAD

**Issue by traefiker** [team-carepay/traefik-opa-plugin#1]
The plugin was not imported into Traefik Pilot.

Cause:
```
failed to read manifest content: yaml: line 6: found unexpected end of stream
```
Traefik Plugin Analyzer will restart when you will close this issue.

If you believe there is a problem with the Analyzer or this issue is the result of a false positive, please contact [us](https://community.containo.us/).

**Comment by blagerweij** [comment]
Made a typo in the description, fixed.
